name = "r2-image-viewer-tinygo"
main = "./build/worker.mjs"
compatibility_date = "2022-05-13"
compatibility_flags = [
    "streams_enable_constructors"
]

[build]
command = "make build"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'r2-image-viewer'
preview_bucket_name = 'r2-image-viewer-dev'